name: 'Upload to JFrog'
description: 'Upload build artefacts to JFrog general registry.'
inputs:
  access_token:
    description: 'Access token for JFrog service account. Find it in org secrets.'
    required: true
  user_name:
    description: 'Define release tag.'
    required: true
  registry_url:
    description: 'Define release repository.'
    required: true
  artefacts_patterns:
    description: 'Define patterns for files which are going to be uploaded - pytyhon regex.'
    required: false
    default: '*'
  action_shell:
    description: 'Define shell for running python script'
    required: true
    default: 'bash'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      if: |
        runner.environment == 'github-hosted' ||
        inputs.action_shell == 'powershell'
      with:
        python-version: '3.11'

    - name: 'Install python deps for Windows'
      if: inputs.action_shell == 'powershell'
      run: python3 -m pip install requests ndg-httpsclient pyopenssl pyasn1
      shell: ${{ inputs.action_shell }}

    - name: 'Install python deps'
      if: inputs.action_shell == 'bash'
      run: python3 -m pip install requests pyopenssl
      shell: ${{ inputs.action_shell }}

    - name: 'Upload artefacts'
      run: |
        python3 ${{ github.action_path }}/artefacts2jfrog.py
      shell: ${{ inputs.action_shell }}
      env:
        ARTEFACTS_PATTERNS: ${{ inputs.artefacts_patterns }}
        REGISTRY_URL: ${{ inputs.registry_url }}
        ACCESS_TOKEN: ${{ inputs.access_token }}
        SERVICE_ACCOUNT: ${{ inputs.user_name }}
